Repository mlf-core/mlf-core, pull requests merged in 2021-03, with the labels that each got.

#235 Document mlf_core functionality
  docs/tutorial.rst
Labels: documentation

#305 Fix Torchvision download, upgrade mlflow-pytorch dependencies and fix GA space issues
  .github/workflows/create_mlflow.yml
  CHANGELOG.rst
  mlf_core/create/templates/common_mlflow_files/{{ cookiecutter.common_mlflow }}/.github/workflows/publish_docker.yml
  mlf_core/create/templates/common_mlflow_files/{{ cookiecutter.common_mlflow }}/.github/workflows/train_cpu.yml
  mlf_core/create/templates/mlflow/mlflow_pytorch/{{ cookiecutter.project_slug }}/environment.yml
Labels: high-priority, mlflow-pytorch

#327 fix(workflows): Cleanup whitespace in publish_docker
  mlf_core/create/templates/common_mlflow_files/{{ cookiecutter.common_mlflow }}/.github/workflows/publish_docker.yml
Labels: bug
